// Question: https://adventofcode.com/2022/day/3

const input = [
  "fBDGBcBrGDvjPtPtPV",
  "QhzJLlLJZgLZzNTgZClQHvRvHFvrjrvnNjHnFjPF",
  "ChldsCZhsQzsCGrrSfMfGpfrdM",
  "MJbgcgJlvMSbfjMSbllmCrntwmFrrFwgtCtFFG",
  "vPhddVZZhmnmdnHmHn",
  "vNBZppZQhjSzfScjDN",
  "jwhqbZRvbzvbqqpqzqHHCCCzsLmmQVtmJVJtLWLPrVLLVrmp",
  "dGMfMGMdBBMSTfdMGTNlcZGGPSmQJVVWsJQPLmPLVPtmWPLW",
  "llMBBcfBnBcZMGgqvCDbjbwgCHjvzH",
  "RSDprRrwgVVRwrGqrJsNFJslgglmmNszzN",
  "LLnWjcHWnCTmpClhHp",
  "MpfMZWjtLMjpjtBPnLPndMBGRqwbwBwvrGwGrGVbVvwD",
  "PQNGshQWtwWNcjssJHHJdlBLBlLrRDFFCrdwSlLB",
  "mbzqZqsgMzfnbmbfgpZvZBLrLlSCrprDlLCrdFBlDL",
  "MfvZzqMmsVnVzzTTbMzfvnctjhcHPQJJjNTGWjQJJHWP",
  "MdLWQdMZrPQWsPdMQPLSqGpHGbGqpqqqVzpm",
  "BhgFhVgnlgBNFtNwzpbTGbTTHpwwbF",
  "tCfvvCfgvBjnfflftCvjWZVddMQZsMMsRdMZMP",
  "lTLdHVlqmqWdvjvJttvFlJtC",
  "ngbMTgGhQpgrGtvCzcCJccCrcj",
  "npgwnDpSDbgbbnGGDQnMDSMgZZWVqNTNPRRdwLLNLqmPZTLP",
  "RRSFZvRdrdbSvSVLRZrSGZZrHcHPfPPwJJVJmPHmJfHVThPm",
  "WnLjBQBCQWqCQwpPmHTcfQpm",
  "gBDttlnqLqlvzzlGRRlr",
  "wGpdGdddMPDWgFJGBzmMlntTbZMtZbnT",
  "qNSqQrrqSjQVrsvTtzNnnZTnfNztZw",
  "rcVrjjsswVvRRHsFJLCDCpCddGCCcG",
  "jLMhCPWLCSWSrRLPWmPPLSCLtcTvHHDhZcfHHltlfZtlfgfH",
  "rBBNrbVdtZlvVcZc",
  "FppGdpFsnsqGJnsFzGdJszbdwSLRSRPrSRjqrMqCwQMWQqRS",
  "jTjZwnpjMDfZnmZfsRhGGztqCzwsdGws",
  "JHrWcNrNNrJHLHlzsCtzGRRRHv",
  "rNLrVBJFLmfCnbTpVQ",
  "LGWJvDFssFmMBhThMvnB",
  "CprbCNZpwfpwfrbZJMQMTQcVVgBZcVQBZc",
  "ptNwfwzHzqzlttbrlpCCqzwtFLGSWFsPDLWFHSDjJWSDLFDs",
  "MZJjSsCsMsZSSdZJhdjZtCbPHljqlLPlPRRDLqHHqLbB",
  "mmwmVpGrnngmggGwnccPbDBPLLLllLBcFRFb",
  "GQzVTQTTVzVrQrmvpTnmrQmMvZRhZZCZSZfCsfttSJddNC",
  "gHZZQRdVgRQWWRPHWPnttDTmqQqDQnStzNqD",
  "bscfjslJJspBLsslNStSmTmLmmDTzNnS",
  "JJCrbbhBsplrrChpBbfjlpbbFWWVggPPhZVRRFPdVMddPnMg",
  "FtLfHNhFJCClJlst",
  "jnDQqnDSDSRqwBwnjdFlZbsrTZdsJsGCbw",
  "zDFSmjSDVqnRMHmphPhfWPgW",
  "rSpRtSPWpStVqrwSSdrrhZvnBBnDBvsqjlBqvvnnzl",
  "LFNLLFfFFhMFbcbmbHbHgTNcvZvBZMsvBnJBzsZvjJvZlvnZ",
  "gmFLhTTbFmmQrrSWWpwWVtwQ",
  "DzmDJGSccGJPcdcJPJqwplhjBHmHVwwtBthV",
  "grMMvRsNRnWCFrgZRrZFhpVVlHVnhpVjVtljhhhf",
  "FFZFZTsvCMSQTdGcTHzT",
  "TLsGTnZncjVmVLgm",
  "DvRwMcHMvMbwBVlCBlzlMjCC",
  "FdRtRHDwQvPnTfPqcFPP",
  "rZNdpBSldLLCJZbbCT",
  "WQcQwqsmQmmqJgTRLRCqLq",
  "znQcwsmPcmnCzQmfGGnzHSDFlNptNthPSdllhFPplS",
  "vWCWvVhhjPNjNNvWVNbnbHnrbGrmlPqnqqbw",
  "JdZSLMgsdgQMcQssQnnDqmDqlDqnDlwrHc",
  "tdgQSSdpQtSMSNWpWRfRCwjpjV",
  "qhdJFpChSJhDFDrqbpJbddSHPPRnGGBfBrHfZRnjRnlBZH",
  "zsMVzmwmtLMtmQTzvwlRcZnZZljvvfGcBjcZ",
  "ttQzMtVgMWVMQsmtJgqJgCJbqhgbBSBN",
  "BWvdCmZBrNRrGSSfTzQJJRTz",
  "gMblllMgLVswbgwMsLjgLLnlVtfHfttSQttTJTSQGfGPTPTB",
  "LMgnMgscgqbFBqvBNFBmNm",
  "VlcczDZjjVbznwLnwpTH",
  "NfJPJNfJdJMSHSHnjBRSnbbL",
  "NddqPttjsdZDqhcqlFcD",
  "NVrNBBFFFrvJJrVTFTNvWBCbCCgWGqDqhqghCLqbqtCC",
  "mfZVPZPcqtLbcqgc",
  "fwZlwzfRfQQPMZBBwwBjFSjTVrBT",
  "GWWNMfWWwGWMtjJnVnJzlzVsvLnsVn",
  "ZpRqHTBddsvtPLqVPP",
  "bpSDgStgTbdFTpDdRmfwfmfGFcMQGWMcjQ",
  "gCgGBgfCbRLbBLGnGBBfRGwprctZFMvtFtvSNNTZZtMvLc",
  "DhJhDzzQlDdshVJlDdhqzqzQZFpppFMNtMZMtFFVvtpSMpFV",
  "qQdsDHWWslnNgHmBbHBf",
  "MRvnJFZVnvzJrWWSqMSPTSNqNj",
  "GlcbDpCHCCczdsDppcccBGccqjwTTwQPPSjNjWSWSwwsPsws",
  "GbdlBbgdVtngtzVg",
  "GqTSRpgJgDNSNJqJlSTJlJCBmmcnjCjLFcMFmnGsmBsM",
  "HPhfPrWdfrQPPPhQWHbLFFWFCmFjMBFFsLBFwj",
  "fdzVbvfshrbzvfbfdVPvQtqqJgqgDpNTgqZZtglZtZDD",
  "wsPhrDMfrwdvHdTFrrtH",
  "lnQbNBbqVBqHGJSddvTlJJJJ",
  "cjnHznzbQmgzqQjBWwZwRjDRfWWhWsWD",
  "SsScnttbbSzRRMMMLpsBLP",
  "dDJGgjGJVMSBBBMj",
  "JGDNCfgfSChDJrgqdgqJqGbNbbcbNtzWFctbzzlWtFFn",
  "dtsBsCMtwSVBlLZZZnMgcMZZ",
  "brppQHGznLZgJzJJ",
  "fprvRpNHpNnvbGDBCBPwBWFWBFBvtB",
  "qjgjSgHNlSGHnjfSVDvDPRDDtcdDcGtD",
  "FMTnnLQZtRZDbcZv",
  "zhBLzrCwnCsTCMCQTFLwwCzpHgNlNmHqhlqSpWllmlllhh",
  "bJqqFdfbGdfPNsJsdSRCFLRHLDDBHDnShL",
  "lQWlWQpwQjlpwrjrwTSCTLMCCNTHRDDDDRRB",
  "wtWgQmQQWtwWwrljNPfGPzJmbbfzmzZf",
  "MjppbDGmNNblCpzsNZzhNPgHtzzs",
  "qvdrqrQVVWLfqWfRRPRwZPPwggpf",
  "cqdcdpqSrrSvrvWvvvrSbcGTTTbGlFFCCcnnGbTb",
  "HLNfNGttHVFBHWSr",
  "RZCLsbCbLbLhwzDgbZCbRZhhnpSnnWpWplFFnDnqlBFVpSVB",
  "MzbhhzwcLGGfGMvMTv",
  "PdBlpdVJlmftGbTzwbtRTGGL",
  "NQNMgWNNQNScDhsSHSWhsNgbRCLwGnnwqLwLHbbCGGTjTR",
  "MvhRMMRvQshgSNDWFrfBfJFZrFPJJJPBBp",
  "qdtnQqWtnjfGGzsnGQmWWfqQNbRTgggRFNbCFNSSFlSJsrTr",
  "PZBBbPMvVcMpSRSlSCpCSgCT",
  "MvHZhwMVLDHDcZMvLQfwGWqwWjqjGbmnQq",
  "NFPmjNhGthGNpddddFpzBbqPczSqPDzzDgbgLZ",
  "VJWvwQrlLHWrvlQZDgZSSDSDBqbb",
  "WfHwMWfvRvMWrWJsrfMRWGFmGGLttMNpjCpTdmFFht",
  "DppfNpLwhTBRDbblgWNgCdgCvs",
  "nLcLqFJrHJmLcFmqMFCdzdHdsgvdzvbvWPWs",
  "nVFqrrQcSVmFjrmJnrFrSjTtRGRLBwfRTfZwhBQhRGGw",
  "sHrZdHGpHhsrLpsssGLzhrdtWdJTMWJvffVdmnbfJVnW",
  "cggRDCCjlPQCgDRnfbTtfMJfWVTm",
  "cCDwQNlwQPjgCFDljwpSLFzGFzZhzsstSpGz",
  "dGTGpGdPZZCpnnLRpgzgzn",
  "lflshFjFcrNdBjMjMnmL",
  "hDfrldDfbVPbQCtHHZ",
  "cSRZmtFZScfjZtLbmCNMqhMVQCjwqqCwVB",
  "pddczHpHHzgWdGdsvPrPzcvrJMNwJCQwJhNwBhCJBVMpCVJB",
  "cgrWcHdnPHHznlmftmtLnRDD",
  "PZFMMVJVZmVJVHMNJNVfNdNNSnSWsSRhgRRQnWSsRnSWmszc",
  "llljlTwlprClTbTpwLlgQqhcnwnczhcgSqsQRR",
  "TpCtGtrTBDZVZHNQZQdB",
  "SggjglBBlzbDgdpFJddZpF",
  "CCNLsfNfrcMLsTLPfPmndmTwmZtZJZJdJplp",
  "sfWCqcvMrlMfMLsLNfhVGvjjjSzSzVQhQvVH",
  "NTBhNhfBvfflsbSmcl",
  "nrMZRnHHwBMZRsSsgSsGrbmdms",
  "nPPFVwVWJqJBVJLT",
  "vvWqWJWJvzfFZZJvWQzqZvdPPHjSfHjssHsbsfbjSHRR",
  "DCwtDVjMCrltCnCrDCDmbTssPHLTLldssdSldSRp",
  "nMcGtDmBmMGrGvvvvFhjFZgWcN",
  "tGWWWfWpMDjMZbTbnqTC",
  "JFscJzFPDJDJZnrJ",
  "sBFPcBsSPBvmSPwFzSSQfpwWfDpgNNfWtfgpftfg",
  "BvTsJJzQJLMlbhmbFlNmTl",
  "PjGnpdpGcgDmhvnvmvlbmq",
  "dRtDGGgcDtjRcwdgQLVLRMJsszJVLRQv",
  "FGbPPfFSchBGSvGGWsjSTLVQLLVTsQlj",
  "dDzPnCrRCrrWHHTTHsdVjs",
  "wrwCgzMrNprCwRJJwnnbFmmpGZtcvcbFfPFmFG",
  "fbrJjmmmZgmZLJZsBBWlCBGnCWdnfF",
  "RVMDDNDHPNvvRvDtHMcctMqFslqWPnClddlClFlnBqCG",
  "MDDvHzHVQMMDtTHJLrnggSZLTJZgTL",
  "dgBBCBBdvbmrRczFMHMSrqjjSPzn",
  "tZTwQlLVwnQLQQFJVPzjDSSzJFPD",
  "fhWhQpTTZQlWfQWpWQWQLhBgchhRCsdbvNnbgRsmRR",
  "LttflLnGrnMsmmHgWTbdMW",
  "vBSWzZRDccWBFBmJsmPJmgbsgB",
  "FppcFWRNRZLLppGrGrqr",
  "JJClRmLlFGvMTlFLLfPFQQcDpQcjFcjqBc",
  "zgHSZhggggtwSZhrDgsZgbjVQcVcjPNqcpQQqBjNQzNp",
  "hZnsShSWGDMMMRnv",
  "RbDbslClhsfNCbsMjbNrjNMfpTTTTJSzHTpLVzLLVWVzJz",
  "ggFGgmqFZBnnSzTWPpHBLzdT",
  "vmWZWGwcZZqthjDrbclNCjlD",
  "dCHwnVBBCBnVHddqnQRdbbbrgTsfWwjcWlsfwDDg",
  "hhlFpMtGJlZmDjfWfscjWDGD",
  "hFNFvZmppmSlNJMmNFztmzFhdVPPHQQqqHPvLBQnBQQPQPnC",
  "WfzsplQpvQgfwzlbllPGtPJTTwtGGZBTTGJB",
  "VrmMjmFDjNjjDFBhHTcZtBRRGcGV",
  "mqrFmmLrjmjZnmqLrmQsfvbsfsSSlpWqgglp",
  "lsQVfDpfflpGGmQRRgdQbdfbWdqnjnHnqZHJTqqrWjqqcWnZ",
  "PPFhFFtwzqjHgjWTWF",
  "SwMwMhNMlMsgfQfl",
  "cSttSDQQCgVvQQSvsstthQcslLLgLgLnpglffjfFlLFblnlH",
  "rTTwTbdBpTHJfZZJ",
  "BddPBzwMBzqRqddRGbVShvVhVQvQscvGtV",
  "sSpsHqHMspqMqWsspwsSWsbBPvjrFbddrGTvZLFjdZTZGLLG",
  "NccDncRVNDVJLvLPPJTJGvJL",
  "mRCDNNhgDnghNRQNggNRcNlMtpMPMMtHtShlSSMtlhHW",
  "QrjSFQWzDdCHtpFlbBbVns",
  "PhJwNLfNqgfdLlZHpZJJpptBBb",
  "qmwhfhhfMNWSmSdQCddv",
  "VfRMdbshRmJBqbmDBH",
  "CWwWCWTCrzFpzWwCWFzgppqHDtZBfqDmQtBftBDFqBtq",
  "WlzrWWGWPrpGCGdfSsRGVnGVdNnR",
  "lhLTfppGRhhbZntsbTqMbq",
  "jrHWBHrMgjHPWMgWBJWBWjstPvwFFbbbvtvFqbPtvqws",
  "rBJJJVWjBjLphcMhSVRV",
  "fjrBPBjWVPWPrwtjPpRQZZVdZQddFdHFTZdT",
  "GqlllsGLgMCqGqgTFbmHdTmRzgTm",
  "qHchGscqGClHGhNwhjJJNWpwPB",
  "JzrrJZqLFrnMzVjNNnNnNDwdGHGlHlHbpTZDlmpTHb",
  "gQfQcRWPWgQSStCtfcsPsPmhsGdDhdGDHTwHpDlHwhTG",
  "fvWQgCtfWgtttcPQcPBtjVdBMJMLJBFJMJVzNrJr",
  "cMzNjGGNQFVzNNQVjNdqRLbFDqRpgLRDpDHD",
  "TwtwWJJBJSvmJCWSvTTmTbBpfpRZSfDqqSqDgHLgqdDDqD",
  "vtvmPrtWQMrbhMrG",
  "NqCPqJNJQQQQGCtGPmMTrTpHlNdmpTrwdN",
  "bzhZRDbnZHrmmcwRfM",
  "vWhsnVWWswhSFvDSDsnhbDsLPqqPFjQjgFgtjqqCLJPgQQ",
  "nqpfqfcnclcNcjjQ",
  "BLQJQmLPPvdtTFNjlFNwPs",
  "DgDgLLCQBBmpVSMrgfqnpp",
  "njCnCwwcVCBWjrrhWrHdzJqmhl",
  "QNGptTTQGLTdhqmdJBHT",
  "GtLvDDvLMvppGGVZMssfCBMfcfMf",
  "npPQGpDnsbJhvldphHFfpl",
  "mgqZcqzczzzcqmRzrbrzBvfBLvlhhftFWlhlFtLBvv",
  "cgjmTgbbMgmzqRRwGDDVQVGVSPwTJV",
  "VhPNvgVhbjPsNvsChTZlHtlwZccZMhwlcm",
  "fpznDWDzDfRqffpnrmcRmwlTMZrHTBHB",
  "fWdQLFSnDzpndqzzqgsVvPsJLMsPCgvjPP",
  "RFRDQVvqVMZGBVzqgqPNJNmNhqqPjnPS",
  "rcLLCWrtwlWrWlTbTtlLWrWtjPPgdwgjmNmShpJnjSpSjgSg",
  "LbLTnbbTHsWlfbtZRZGQHHZZDQMVFz",
  "dwcLLSLVdwLdvdfZNJgQZWfffVJQ",
  "CTMlCRCCCTCtBmCFMQJNNNbNfWvQjvZggT",
  "mRnnnpFlvhnlMmBmFMCMCcdHrwzqszprdcwzLDwrSz",
  "JSHLHRMlzJHcGMpwCffZctZmgfqqZm",
  "vnTWvQrnrQjNnBWvnvDnVgqtVWwVgfFmqWfqZFWZ",
  "rdQDBdBrQQhmBNjDTmrTnzPzPPLHSSHzHHRHRLdGLl",
  "GvMRRwGwRFmZRnmbMhZMGcpgZBpdgBJcTsjsBstdds",
  "SNlPzzlPDDQSDDDqfllqDLBpTgWBgWdTpcWjJQsWjjTp",
  "rScrCqPCSLDNrqlFmRVRRrbhmRmFRw",
  "dbtgMNlNSMQPSLNdvVQgSfcHHfJfHJtfmmHTqZffJH",
  "wssswnzwChsrGCCwGCjzCsHFHbzZffbFBcffbHHTBJTZ",
  "rsDRGDwjhWbrbRhGCGLdLNlNQVVDPSlMVMvv",
  "BgPccPPRlZZmTMTZzZTC",
  "jjNjntVtQnWHrJjFPnnqDqJTJTzqJmDDCqChzS",
  "FnQHQjHVNnWVvQpgLPGRdcLpbfLLBl",
  "JLMhFJfHHLJChRvfjLJJnFRpPrpPSrNnrTrTTPntTptrpw",
  "QgcBCqcGBBGzGrNQNSwSrPPTsr",
  "zzWdmzcWcdHCJCRRCF",
  "GSRcjdjGcBnFWbnVLFQR",
  "pCNqTqhDsMsMmNtNCZmMMtdCbVFzbFwnFFnWWFnzVLTQWQLF",
  "qNJpMdCsDNsNNvGPlSPPJjfBBB",
  "lsHjgmFsnFTwHgSPDRSrDqnqrrnr",
  "NmZWcZmzNMZWJbbWvJMJJMzBBBrRrdRfDfppBNqSrrrPBP",
  "JZQZzQtWJhmltVwVCjwGjs",
  "DslBHDpdDlslgffFWnGqHfzH",
  "JNMMCCCCSMvzzGfMzP",
  "hNtCJTwRwZQbwrplpDjlpz",
  "vwvJwLBzwhhwvzwrgwshLwVWWgFfmlSFVRDfWFSVFVfF",
  "mNqbdPnNdpdjnMqSFFMDfSFVMDFRSV",
  "ddpTPTqmbNjjNqndZzvLzJZzHCrrCCzsJH",
  "SLjjlGMVpLpNSTDspsrHpFFwRrZgRfwpfgFZ",
  "nQtWPzbPNQtbdzPtbBCQJNPcwFvZJZFFJrwRwrHcfcfrgF",
  "NQCnqPBWddbPnbCdWdWQnmdVhsMMDsslmSSmMLlVTTDVMm",
  "FZmcqBChfFmfsDjjnNMNjSDgNs",
  "RZwzdvdZRvTRRlvWSgDjStnpntDwNMtD",
  "vHTGRvvvZHlQPRQTbPTVfLJPqcLJBhfmFVJPCF",
  "dStFcccjFjqGFrFHmSHFBjBvzhpprWZpppbppDvzhsvDhT",
  "VMVLNfCCCRTTDtDDDTRz",
  "QLJwMMLnLNVLdtGGgmdScBnB",
  "nTCWnTnrllglrNgNTZFgSZbddHtdHLLwtMLQtfbM",
  "BJGqppPCJVmqqhBJCdwwpLSLHddfHSLHtw",
  "qmzBhczVGsqVBqnFcCjRWNrNlrgD",
  "phrHLNtnMpslNFfwVGwFZSBfFTTz",
  "cmJJDmmbCnCCfBSJGVBwfBfz",
  "DdqdDbcqCPcCQRWmQPqNHhnRMntNNMNhlsLsML",
  "gHHWJWMWsHWgWSnPwVnVNGGDbnwwTl",
  "QjThjhFqqhmQTCVPfDVqPbDVVl",
  "mpFLLrZjjBcmLFmmFtLBJMddMgSdHTscvcJzRHRs",
  "gRdwcCddwghzddzzzsGfZsGnqlqVVhjGDj",
  "DMBNpMDHrNrNLFMmpQJHZGnPjFPFlZjlfGVljGVf",
  "SpbQNmHMzgcRwSSD",
  "drqcMpNbpFpmjzfz",
  "HLGZGsnGLwllzHGGgGnGsBFfmJtmtjfJDSBSJJJB",
  "ZZwQwHTgZnwLGTTnQTHVlgbWCQNhzNcMqbrzcNNQdNcr",
  "TDScznfzNlpbbrtsvjdcbh",
  "BBHqFGWGFmVWqVBBWMtvCLvsLdvrvjLjdLbsvm",
  "tPZHGFJPJqVwMWHJVRRSZNfQnzfpnTpNfl",
  "FWNZgWCngsNwJwlQlrRTRhSjSS",
  "GGLcVVcVmppMmpTjTRHlbRbSrVBh",
  "rvmdzPcdzmzMrCNNPJFntFsCtD",
  "MtfLBzSLmMtfBMQzMmzmSlfdTDvGCZGCndZnZgWDwGCZ",
  "HhqrrpppcqhdbjPvbgGvTCnWDbTWZT",
  "cNjsdqPqchJBlmzlVQLtBJ",
  "DwwVFZlDBsZFDvLPdpjLjSVHjpLc",
  "nMnztWhhfPSffcddGpgp",
  "tQnrQzhzNtzbNrBwPJwTslTvNFFP",
  "LWMvHJJrJwtzvgwMwVdGfcpNfdDVDWfdBB",
  "jZPFmjnbmhPfTVfVHdhTTV",
  "qqQCmCmbqCQqjQsQvrQSHSJrzz",
  "wNzmDRwmgcGphZcPvLLZHjjFLF",
  "JlbsClVVqDqFZjJD",
  "WSlnCbttftsCsWftbCCrTffbpdzMwgMgSpRmdwdRzggmDGGg",
  "gCCRBClgfCgFFTltTGgBqTsQhzLzQQNPnvrNzHrrfPzHLr",
  "DMjqWSVwDwDwZDHZNvLQnrnrPrNv",
  "bcmWJqdVcbtgBglbGTCl",
  "SFDcrFHtlqhqqLdzTTwdJLPNDL",
  "vBWsWvsmgvvvdPwNnn",
  "smfRbpsWMBmsmMsBBBNbtSFttjCHSScbhHtHhHjb",
  "SQpgGgMNvggQGMvQcgnHWmldnHWTWndnSHHF",
  "DwbDPzthtttljTzTFBlmzl",
  "DstCswftDbZbCChPPRrfwsfPQlLccJQLvVGNGNVpMNvZcvgG",
  "HdqfjjLfHqFSHddVWNBjsWhWRRJtBNBs",
  "gPMQHpmrcmnbRQNRRJsWttWW",
  "pmbcZwbrPPrnTPMFFdDwqHwvHDvzDq",
  "FFsVtFGVGvWVhlfVhzlsFvHbPwPmwHLTSbLjcLtbSbLm",
  "rZrpJwCqnnJHmqcbcTLTbS",
  "RCZZQMQpzvRhswVg"
];

// Part 1:

const LOWERCASE_OFFSET = 96;
const UPPERCASE_OFFSET = 38;

const sumPriority = arr => {
  return arr
    .map(string => {
      let i = 0;
      while (!string.includes(string[i], string.length / 2)) i++;
      return string[i];
    })
    .reduce((sum, letter) => {
      return letter === letter.toLowerCase() ?
        sum += (letter.charCodeAt(0) - LOWERCASE_OFFSET) :
        sum += (letter.charCodeAt(0) - UPPERCASE_OFFSET);
    }, 0);
}

// console.log(sumPriority(input));

// Answer: 8085

// Part 2:

const sumBadges = arr => {
  let badgeLetters = [];
  for (let i = 0; i < arr.length; i += 3) {
    for (let x = 0; x < arr[i].length; x++) {
      if (arr[i + 1].includes(arr[i][x]) && arr[i + 2].includes(arr[i][x])) {
        badgeLetters.push(arr[i][x]);
        break;
      }
    }
  }
  return badgeLetters.reduce((sum, letter) => {
    return letter === letter.toLowerCase() ?
        sum += (letter.charCodeAt(0) - LOWERCASE_OFFSET) :
        sum += (letter.charCodeAt(0) - UPPERCASE_OFFSET);
  }, 0);
}

console.log(sumBadges(input));

// Answer: 2515